
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netflix-app.fullname" . }}  # Service name
  labels:
    app.kubernetes.io/name: {{ include "netflix-app.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "netflix-app.name" . }}  # Match labels from Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort

